# Generated by Django 3.2 on 2021-05-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='crawling_interval',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='last_crawled',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='last_updated',
        ),
    ]
